
Vagrant.configure(2) do |config|

config.vm.box = "ubuntu/wily64"
config.vm.hostname = "testbox"
config.vm.network "private_network", ip: "192.168.2.114"
config.vm.synced_folder "../", "/sites/test"

config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = 1024
    vb.cpus = 1
end

config.vm.provision "shell", inline: <<-SHELL

    export DEBIAN_FRONTEND=noninteractive
    #VFDIR="/sites/test/vagrant/files"
    VFDIR="/vagrant/files"

    # install ssh keys
    cp ${VFDIR}/dot/ssh/id_rsa.pub ~vagrant/.ssh/id_rsa.pub
    cp ${VFDIR}/dot/ssh/id_rsa ~vagrant/.ssh/id_rsa
    chmod 400 ~vagrant/.ssh/id_rsa
    chmod 444 ~vagrant/.ssh/id_rsa.pub
    chown vagrant:vagrant ~vagrant/.ssh/id_rsa ~vagrant/.ssh/id_rsa.pub
    cat ~vagrant/.ssh/id_rsa.pub >> ~vagrant/.ssh/authorized_keys

    # add php-5.6 repo
    apt-get -y update
    apt-get install -y python-software-properties
    add-apt-repository ppa:ondrej/php5-5.6
    apt-get -y update

    # php-fpm
    apt-get install -y php5-fpm

    # php extensions
    apt-get install -y php5-mysqlnd
    apt-get install -y php5-curl
    apt-get install -y php5-intl
    apt-get install -y php5-imagick
    apt-get install -y php5-mcrypt
    apt-get install -y php5-apcu
    apt-get install -y php5-xdebug

    # nginx
    apt-get install -y nginx

    # mysql
    # echo "mysql-server mysql-server/root_password password 123" | sudo debconf-set-selections
    # echo "mysql-server mysql-server/root_password_again password 123" | sudo debconf-set-selections
    apt-get install -y mysql-server

    # nodejs and npm
    curl --silent --location https://deb.nodesource.com/setup_4.x | sudo bash -
    apt-get install -y nodejs

    # gulp
    #npm install -g gulp
    #npm install -g gulp-autoprefixer
    #npm install -g gulp-concat-css
    #npm install -g gulp-cssnano
    #npm install -g gulp-rename
    #npm install -g gulp-sass
    #npm install -g gulp-less
    #npm install -g gulp-compass
    #npm install -g gulp-stylus
    #npm install -g gulp-coffee
    #npm install -g gulp-jade
    #npm install -g gulp-uncss
    #npm install -g gulp-uglify
    #npm install -g del

    # tools
    apt-get install -y subversion
    apt-get install -y git
    apt-get install -y screen
    apt-get install -y mc
    apt-get install -y golang-go

    # Rub shell scripts
    echo
    echo "Executing shell scripts ..."
    for F in `ls -l ${VFDIR}/shell/*.sh|awk 'BEGIN{ORS=" "}{print $9}'`; do
        echo $F
        bash ${VFDIR}/shell/`basename $F`
    done
    echo done

    # Config for PHP-FPM pools
    echo
    echo "Installing PHP-FPM pools config ..."
    for F in `ls -l ${VFDIR}/php/pool.d/*.conf|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo "cp ${VFDIR}/php/pool.d/${FNAME} /etc/php5/fpm/pool.d/${FNAME}"
        cp ${VFDIR}/php/pool.d/${FNAME} /etc/php5/fpm/pool.d/${FNAME}
    done
    echo done

    # Virtual hosts
    echo
    echo -n "Installing nginx virtual hosts ..."
    for F in `ls -l ${VFDIR}/nginx/*.conf|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo -n " ${FNAME}"
        cp ${VFDIR}/nginx/${FNAME} /etc/nginx/sites-available
        ln -s /etc/nginx/sites-available/${FNAME} /etc/nginx/sites-enabled/${FNAME}
    done
    echo
    echo done

    # run sql scripts to create users, databases, etc.
    echo
    echo "Executing SQL scripts ..."
    for F in `ls -l ${VFDIR}/mysql/*.sql|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo "mysql < ${VFDIR}/mysql/${FNAME}"
        mysql < ${VFDIR}/mysql/${FNAME}
    done

    # run sql scripts for databases
    echo
    echo "Executing SQL scripts for databases ..."
    for D in `ls -l ${VFDIR}/mysql|grep '^d'|awk 'BEGIN{ORS=" "}{print $9}'`; do
        DBNAME=`basename $D`
        for F in `ls -l ${VFDIR}/mysql/${DBNAME}/*.sql|awk 'BEGIN{ORS=" "}{print $9}'`; do
            FNAME=`basename $F`
            echo "mysql $DBNAME < ${VFDIR}/mysql/${DBNAME}/${FNAME}"
            mysql $DBNAME < ${VFDIR}/mysql/${DBNAME}/${FNAME}
        done
    done

    # restart services
    echo
    echo -n "Restarting services ... "
    service php5-fpm restart
    service nginx restart
    service mysql restart

    echo done
    echo

    id
    echo All done.
SHELL

end
