
Vagrant.configure(2) do |config|

config.vm.box = "ubuntu/xenial64"
config.vm.hostname = "testbox"
config.vm.network "private_network", ip: "192.168.2.114"
config.vm.synced_folder "../", "/sites/test"

config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "vagrant_devbox"
    vb.memory = 4096
    vb.cpus = 2
end

config.vm.provision "shell", inline: <<-SHELL

    export DEBIAN_FRONTEND=noninteractive
    PRJROOT="/sites/test"
    VFDIR="/vagrant/files"
    VUSER="ubuntu"

    if [ -f /usr/share/zoneinfo/CET ]; then
        rm -f /etc/localtime
        ln -s /usr/share/zoneinfo/CET /etc/localtime
    fi

    if id -u vagrant >/dev/null 2>&1; then
        VUSER="vagrant"
    fi

    ### installing dot files
    echo "Installing dot files ... "

    for F in `ls -l ${VFDIR}/dot/.*|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`

        if [ -f ${VFDIR}/dot/${FNAME} ]; then
            echo "cp ${VFDIR}/dot/${FNAME} /home/${VUSER}/${FNAME}"
            cp ${VFDIR}/dot/${FNAME} /home/${VUSER}/${FNAME}
            echo chown ${VUSER}:${VUSER} /home/${VUSER}/${FNAME}
            chown ${VUSER}:${VUSER} /home/${VUSER}/${FNAME}
            echo chmod 644 /home/${VUSER}/${FNAME}
            chmod 644 /home/${VUSER}/${FNAME}
        fi
    done

    echo done
    echo

    ### installing packages
    apt -y update
    apt -y upgrade

    # php
    add-apt-repository -y ppa:ondrej/php
    apt-get update -y

    apt install -y php7.3

    apt install -y php7.3-fpm
    apt install -y php7.3-curl
    apt install -y php7.3-intl
    apt install -y php7.3-mbstring
    apt install -y php7.3-mysql
    apt install -y php7.3-xml
    apt install -y php7.3-opcache
    apt install -y php-imagick
    apt install -y php-xdebug

    # nginx
    apt install -y nginx

    # mysql
    apt install -qq -y mysql-server

    # nodejs & npm
    curl -sL https://deb.nodesource.com/setup_9.x | sudo bash -
    apt install -y nodejs

    # install gulp
    npm install gulp-cli -g

    # tools
    apt install -y git
    apt install -y mc
    apt install -y golang-go

    # Run shell scripts
    echo
    echo "Executing shell scripts ... "
    for F in `ls -l ${VFDIR}/shell/*.sh|awk 'BEGIN{ORS=" "}{print $9}'`; do
        echo $F
        bash ${VFDIR}/shell/`basename $F`
    done
    echo done
    echo

    # Config for PHP-FPM pools
    echo "Installing PHP-FPM pools ... "

    for F in `ls -l ${VFDIR}/php/pool.d/*.conf|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo $FNAME
        cat ${VFDIR}/php/pool.d/${FNAME} | sed s/%vuser%/${VUSER}/ >/etc/php/7.3/fpm/pool.d/${FNAME}
    done

    echo done
    echo

    # Virtual hosts
    echo "Installing virtual hosts ... "

    for F in `ls -l ${VFDIR}/nginx/*.conf|awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo -n " ${FNAME}"
        cp ${VFDIR}/nginx/${FNAME} /etc/nginx/sites-available
        ln -s /etc/nginx/sites-available/${FNAME} /etc/nginx/sites-enabled/${FNAME}
    done

    echo done
    echo

    # Restart mysql
    echo "Restarting MySQL ... "
    service mysql restart
    echo done
    echo

    # run sql scripts to create users, databases, etc.
    echo
    echo "Executing SQL scripts ... "

    for F in `ls -l ${VFDIR}/mysql/*.sql | awk 'BEGIN{ORS=" "}{print $9}'`; do
        FNAME=`basename $F`
        echo "mysql < ${VFDIR}/mysql/${FNAME}"
        mysql < ${VFDIR}/mysql/${FNAME}
    done

    echo done
    echo

    # run sql scripts for databases
    echo "Executing SQL scripts for databases ... "
    for D in `ls -l ${VFDIR}/mysql|grep '^d'|awk 'BEGIN{ORS=" "}{print $9}'`; do
        DBNAME=`basename $D`
        for F in `ls -l ${VFDIR}/mysql/${DBNAME}/*.sql|awk 'BEGIN{ORS=" "}{print $9}'`; do
            FNAME=`basename $F`
            echo "mysql $DBNAME < ${VFDIR}/mysql/${DBNAME}/${FNAME}"
            mysql $DBNAME < ${VFDIR}/mysql/${DBNAME}/${FNAME}
        done
    done

    echo done
    echo

    echo 127.0.0.1 devbox.vmdev.com >> /etc/hosts

    # Restart services
    echo
    echo -n "Restarting services ... "

    service php7.3-fpm restart
    service nginx restart
    service mysql restart

    echo done
    echo

    id
    echo All done.

SHELL

end
